<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2024-11-10">

<title>Malaria Molecular Surveillance Study Design workshop - Activity 4: Intra-cluster correlation</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<script src="../../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Malaria Molecular Surveillance Study Design workshop</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html" rel="" target=""><i class="bi bi-house" role="img">
</i> 
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../schedule.html" rel="" target=""><i class="bi bi-calendar" role="img">
</i> 
 <span class="menu-text">Schedule</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../lectures.html" rel="" target=""><i class="bi bi-bookmark" role="img">
</i> 
 <span class="menu-text">Lectures</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-tutorials" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
      <i class="bi bi-book" role="img">
</i> 
 <span class="menu-text">Tutorials</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-tutorials">    
        <li>
    <a class="dropdown-item" href="../../tutorials.html" rel="" target="">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://mms-sdworkshop.shinyapps.io/module1_sampling_interactive/" rel="" target=""><i class="bi bi-play" role="img">
</i> 
 <span class="dropdown-text">Module 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://mms-sdworkshop.shinyapps.io/module2_MOE_interactive/" rel="" target=""><i class="bi bi-play" role="img">
</i> 
 <span class="dropdown-text">Module 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://mms-sdworkshop.shinyapps.io/module1_sampling_interactive/" rel="" target=""><i class="bi bi-play" role="img">
</i> 
 <span class="dropdown-text">Module 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://mms-sdworkshop.shinyapps.io/module1_sampling_interactive/" rel="" target=""><i class="bi bi-play" role="img">
</i> 
 <span class="dropdown-text">Module 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://mms-sdworkshop.shinyapps.io/module1_sampling_interactive/" rel="" target=""><i class="bi bi-play" role="img">
</i> 
 <span class="dropdown-text">Module 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tutorials/module6/module6_scenarios.html" rel="" target=""><i class="bi bi-play" role="img">
</i> 
 <span class="dropdown-text">Module 6</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#learning-outcomes" id="toc-learning-outcomes" class="nav-link active" data-scroll-target="#learning-outcomes">Learning outcomes</a></li>
  <li><a href="#analyzing-data-from-a-multi-cluster-pfhrp2-deletion-study" id="toc-analyzing-data-from-a-multi-cluster-pfhrp2-deletion-study" class="nav-link" data-scroll-target="#analyzing-data-from-a-multi-cluster-pfhrp2-deletion-study">Analyzing data from a multi-cluster <em>pfhrp2</em> deletion study</a>
  <ul class="collapse">
  <li><a href="#background" id="toc-background" class="nav-link" data-scroll-target="#background">Background</a></li>
  <li><a href="#estimating-the-global-prevalence" id="toc-estimating-the-global-prevalence" class="nav-link" data-scroll-target="#estimating-the-global-prevalence">Estimating the global prevalence</a></li>
  <li><a href="#detecting-over-dispersion" id="toc-detecting-over-dispersion" class="nav-link" data-scroll-target="#detecting-over-dispersion">Detecting over-dispersion</a></li>
  </ul></li>
  <li><a href="#measuring-the-impact-of-over-dispersion" id="toc-measuring-the-impact-of-over-dispersion" class="nav-link" data-scroll-target="#measuring-the-impact-of-over-dispersion">Measuring the impact of over-dispersion</a>
  <ul class="collapse">
  <li><a href="#the-design-effect" id="toc-the-design-effect" class="nav-link" data-scroll-target="#the-design-effect">The design effect</a></li>
  <li><a href="#the-effective-sample-size" id="toc-the-effective-sample-size" class="nav-link" data-scroll-target="#the-effective-sample-size">The effective sample size</a></li>
  <li><a href="#the-intra-cluster-correlation-coefficient" id="toc-the-intra-cluster-correlation-coefficient" class="nav-link" data-scroll-target="#the-intra-cluster-correlation-coefficient">The intra-cluster correlation coefficient</a></li>
  </ul></li>
  <li><a href="#bonus-questions" id="toc-bonus-questions" class="nav-link" data-scroll-target="#bonus-questions">Bonus questions</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Activity 4: Intra-cluster correlation</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 10, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="learning-outcomes" class="level2">
<h2 class="anchored" data-anchor-id="learning-outcomes">Learning outcomes</h2>
<p>This activity focuses on measuring over-dispersion in multi-cluster studies using the example of a hypothetical <em>pfhrp2/3</em> deletion study in Tanzania. In this activity you will learn:</p>
<ul>
<li>What over-dispersion looks like in prevalence data, and how to detect it statistically</li>
<li>How to measure over-dispersion using different metrics</li>
<li>The impact of over-dispersion on statistical efficiency</li>
</ul>
<p><em>Disclaimer: The scenarios in this document are entirely fictitious. While real place names are used, the data itself is simulated for teaching purposes only. It does not necessarily represent the real epidemiological situation.</em></p>
</section>
<section id="analyzing-data-from-a-multi-cluster-pfhrp2-deletion-study" class="level2">
<h2 class="anchored" data-anchor-id="analyzing-data-from-a-multi-cluster-pfhrp2-deletion-study">Analyzing data from a multi-cluster <em>pfhrp2</em> deletion study</h2>
<section id="background" class="level3">
<h3 class="anchored" data-anchor-id="background">Background</h3>
<p>You are collaborating with the Tanzanian National Malaria Control Programme (NMCP) to investigate the prevalence of <em>pfhrp2/3</em> gene deletions in the Dodoma region of Tanzania. These gene deletions pose a significant threat to malaria control efforts as they can lead to parasites being undetectable by rapid diagnostic tests (RDTs) that rely exclusively on the HRP2 protein. Undetected cases may lead to delays in treatment or missed malaria diagnoses, undermining effective case management.</p>
<p>A multi-cluster study has been performed in 8 sites within the Dodoma region of Tanzania. The results of this study are shown below:</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-sm small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Site</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Confirmed Malaria<br>
(n)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">pfhrp2 Deleted<br>
(x)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">pfhrp2 Deletion Prevalence<br>
(p)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 3cm;">Chalinze</td>
<td style="text-align: right; width: 3cm;">100</td>
<td style="text-align: right; width: 3cm;">7</td>
<td style="text-align: right; width: 3cm;">0.070</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 3cm;">Ibwaga</td>
<td style="text-align: right; width: 3cm;">80</td>
<td style="text-align: right; width: 3cm;">12</td>
<td style="text-align: right; width: 3cm;">0.150</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 3cm;">Lukali</td>
<td style="text-align: right; width: 3cm;">100</td>
<td style="text-align: right; width: 3cm;">7</td>
<td style="text-align: right; width: 3cm;">0.070</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 3cm;">Malolo</td>
<td style="text-align: right; width: 3cm;">100</td>
<td style="text-align: right; width: 3cm;">26</td>
<td style="text-align: right; width: 3cm;">0.260</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 3cm;">Mafene</td>
<td style="text-align: right; width: 3cm;">95</td>
<td style="text-align: right; width: 3cm;">25</td>
<td style="text-align: right; width: 3cm;">0.263</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 3cm;">Mpendo</td>
<td style="text-align: right; width: 3cm;">100</td>
<td style="text-align: right; width: 3cm;">45</td>
<td style="text-align: right; width: 3cm;">0.450</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 3cm;">Nhinhi</td>
<td style="text-align: right; width: 3cm;">50</td>
<td style="text-align: right; width: 3cm;">0</td>
<td style="text-align: right; width: 3cm;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 3cm;">Rudi</td>
<td style="text-align: right; width: 3cm;">100</td>
<td style="text-align: right; width: 3cm;">11</td>
<td style="text-align: right; width: 3cm;">0.110</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><sup></sup><br>
Table 1: pfhrp2 deletion data by Site</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tfoot>

</table>


</div>
</div>
<p>The columns of this table are available in R as the variables <code>n</code>, <code>x</code> and <code>p</code>.</p>
</section>
<section id="estimating-the-global-prevalence" class="level3">
<h3 class="anchored" data-anchor-id="estimating-the-global-prevalence">Estimating the global prevalence</h3>
<p>We want to use the information over all 8 sites to estimate the prevalence of <em>pfhrp2</em> deletions in the Dodoma region as a whole. One way to do this is to take the mean over sites:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(p)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.171625</code></pre>
</div>
</div>
<p>The mean prevalence is around 17%. However, this calculation ignores differences in sample sizes between sites. For example, the Nhinhi site is given just as much weight as the Rudi site, despite having half the number of confirmed malaria cases. A different approach is to use a <em>weighted</em> average, where the weights are given by the sample sizes:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># define weights based on sample size</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>weights <span class="ot">&lt;-</span> n</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate prevalence as a weighted average over sites</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(weights <span class="sc">*</span> p) <span class="sc">/</span> <span class="fu">sum</span>(weights)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1834276</code></pre>
</div>
</div>
<p>We now find that prevalence is closer to 18%. In this example, there is not much difference between the two methods, but in general they can give quite different results. Neither approach is more correct than the other, they just have different strengths and weaknesses. The unweighted mean is more conservative when there could be large intra-cluster correlation. On the other hand, the weighted mean avoids the issue of small clusters having a large influence on the final estimate.</p>
<p>For the purposes of this tutorial, we will use the unweighted mean as our estimate over all sites. This value is often called the “global” prevalence, and is given the symbol <span class="math inline">\(\hat{p}\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>p_global <span class="ot">&lt;-</span> <span class="fu">mean</span>(p)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="detecting-over-dispersion" class="level3">
<h3 class="anchored" data-anchor-id="detecting-over-dispersion">Detecting over-dispersion</h3>
<p>Now that we have an estimate of the global prevalence, we can look for <em>over-dispersion</em> in the data. If all patients enrolled in the study have the same probability <span class="math inline">\(\hat{p}\)</span> of carrying the <em>pfhrp2</em> deletion, then we expect to see a certain level of variation between sites. Most of the time, the site-level prevalence should be within the following 95% interval: <span class="math display">\[
\hat{p} \pm z_{1 - \alpha/2}\sqrt{\frac{\hat{p}(1 - \hat{p})}{n_i}}
\]</span> where <span class="math inline">\(n_i\)</span> is the sample size in the <span class="math inline">\(i^{\text{th}}\)</span> site. Because this is a 95% interval, we should expect sites to fall within this range 95% of the time. For our study involving 8 sites, it would be very unusual to see more than one site with a prevalence outside this range.</p>
<p>The plot below shows the site-level prevalence in red. The global mean prevalence of 17% shown as a horizontal dashed line and the 95% interval shown as an error bar.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="activity4_multicluster_static_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Question:</strong> How many sites have a prevalence outside the expected 95% interval?</p>
<p><strong>Options:</strong></p>
<ul>
<li>0</li>
<li>2</li>
<li>4</li>
<li>6 <strong>(correct)</strong></li>
</ul>
<p><strong>Question:</strong> From this plot, does the prevalence appear to be over-dispersed, under-dispersed, or neither?</p>
<p><strong>Options:</strong></p>
<ul>
<li>Over-dispersed <strong>(correct)</strong></li>
<li>Under-dispersed</li>
<li>Neither</li>
</ul>
<p><strong>Question:</strong> What could cause this over-dispersion?</p>
<p><strong>Options:</strong></p>
<ul>
<li>Limited migration and gene flow between sites.</li>
<li>Variation in treatment practices leading to different selective pressures between sites.</li>
<li>Local outbreaks within sites, driven by infected individuals carrying <em>pfhrp2</em> deletions.</li>
<li>All of the above <strong>(correct)</strong></li>
</ul>
<p><strong>Question:</strong> Why does the Nhinhi site have a slightly wider 95% interval than the other sites?</p>
<p><strong>Options:</strong></p>
<ul>
<li>The Nhinhi site has higher prevalence of <em>pfhrp2</em> deletions.</li>
<li>The diagnostic methods used at the Nhinhi site are less accurate.</li>
<li>The Nhinhi site is geographically isolated.</li>
<li>The sample size in Nhinhi is lower than other sites <strong>(correct)</strong></li>
</ul>
</section>
</section>
<section id="measuring-the-impact-of-over-dispersion" class="level2">
<h2 class="anchored" data-anchor-id="measuring-the-impact-of-over-dispersion">Measuring the impact of over-dispersion</h2>
<section id="the-design-effect" class="level3">
<h3 class="anchored" data-anchor-id="the-design-effect">The design effect</h3>
<p>One way of quantifying the effect of over-dispersion is through the <strong>design effect</strong> (<span class="math inline">\(D_{\text{eff}}\)</span>). We can estimate the design effect by calculating the observed variance between sites and dividing this by the variance that we would expect to see under simple random sampling (SRS), which is when all individuals in the study are perfectly independent.</p>
<p>The observed variance between sites can be calculated as:</p>
<p><span class="math display">\[
s^2 = \frac{1}{c-1}\sum_{i=1}^c (\hat{p}_i - \hat{p})^2
\]</span> where <span class="math inline">\(c\)</span> is the number of sites (8 in our case) and <span class="math inline">\(\hat{p}_i\)</span> is the prevalence in site <span class="math inline">\(i\)</span>. This formula is called the <em>sample variance</em>, and it is found in many areas of statistics. We don’t need to calculate this value by hand, instead we can do it very easily in R using the <code>var()</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate observed variance between sites</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>var_observed <span class="ot">&lt;-</span> <span class="fu">var</span>(p)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(var_observed)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02114684</code></pre>
</div>
</div>
<p>Next, we need to calculate the variance that we would expect to see under simple random sampling (SRS). This is given by:</p>
<p><span class="math display">\[
\text{var}_{\text{SRS}} = \frac{1}{c} \sum_{i=1}^c \frac{\hat{p}(1 - \hat{p})}{n_i}
\]</span> We can calculate this in R as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>var_SRS <span class="ot">&lt;-</span> <span class="fu">mean</span>(p_global<span class="sc">*</span>(<span class="dv">1</span> <span class="sc">-</span> p_global) <span class="sc">/</span> n)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(var_SRS)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.001653192</code></pre>
</div>
</div>
<p>Our observed variance was 0.0211, but the variance we would expect to see under SRS is only 0.00165. This tells us that our data are more variable than we would expect by chance, in other words this confirms that there is <em>over-dispersion</em> in our data. We calculate the design effect as the ratio of these two quantities:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>Deff <span class="ot">&lt;-</span> var_observed <span class="sc">/</span> var_SRS</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(Deff)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12.79152</code></pre>
</div>
</div>
<p>We obtain a design effect of <span class="math inline">\(D_{\text{eff}}=12.79\)</span>.</p>
<p><strong>Question:</strong> The design effect measures:</p>
<p><strong>Options:</strong></p>
<ul>
<li>How good a study is.</li>
<li>The statistical <em>inefficiency</em> of a study, relative to SRS. <strong>(correct)</strong></li>
<li>The number of sites used in a study.</li>
<li>The average prevalence across sites.</li>
</ul>
<p>The design effect is a measure of the statistical <em>inefficiency</em> of a study design. Larger values indicate less efficient designs, with a value of <span class="math inline">\(D_{\text{eff}}=1\)</span> representing a gold standard in terms of statistical efficiency. Our observed value of <span class="math inline">\(D_{\text{eff}}=12.79\)</span> indicates that our study has a high level of statistical inefficiency due to the high level of over-dispersion in the data.</p>
<p><strong>Question:</strong> A high value of the design effect means we can expect to see:</p>
<p><strong>Options:</strong></p>
<ul>
<li>Greater uncertainty around our global estimate of the prevalence <span class="math inline">\(\hat{p}\)</span>.</li>
<li>Lower power.</li>
<li>Larger sample sizes needed.</li>
<li>All of the above. <strong>(correct)</strong></li>
</ul>
</section>
<section id="the-effective-sample-size" class="level3">
<h3 class="anchored" data-anchor-id="the-effective-sample-size">The effective sample size</h3>
<p>Another way to quantify the impact of over-dispersion is through the <em>effective sample size</em>, <span class="math inline">\(N_{\text{eff}}\)</span>. The effective sample size tells us how many perfectly independent samples we would need in order to achieve the same level of statistical efficiency. In other words, it tells us how large our study would need to be if we could get rid of over-dispersion completely. We calculate <span class="math inline">\(N_{\text{eff}}\)</span> by dividing the true total sample size by the design effect:</p>
<p><span class="math display">\[
N_{\text{eff}} = \frac{\sum_{i=1}^c n_i}{D_{\text{eff}}}
\]</span> Here is R code that performs this calculation:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(n) <span class="sc">/</span> Deff</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 56.67818</code></pre>
</div>
</div>
<p>Our effective sample size is just 56.7, even though our total sample size was 725! Amazingly, this means that, due to correlations within sites, it’s as if we had enrolled only 56 patients! This emphasizes the importance of considering over-dispersion. If we ignored over-dispersion in our analysis then we might kid ourselves into thinking we had a large amount of data and hence very precise estimates of the regional prevalence. When we deal with it correctly we get much more robust results.</p>
</section>
<section id="the-intra-cluster-correlation-coefficient" class="level3">
<h3 class="anchored" data-anchor-id="the-intra-cluster-correlation-coefficient">The intra-cluster correlation coefficient</h3>
<p>The third and final measure that we will consider is the <em>intra-cluster correlation coefficient</em> (ICC), often given the symbol <span class="math inline">\(\rho\)</span>. This is a measure between 0 and 1 that describes how correlated observations are <em>within</em> a cluster (site). The relationship between the ICC and the design effect is:</p>
<p><span class="math display">\[
D_{\text{eff}} = 1 + \rho(\bar{n} - 1)
\]</span> where <span class="math inline">\(\bar{n}\)</span> is the mean sample size over sites. Notice that when there is zero intra-cluster correlation (<span class="math inline">\(\rho=0\)</span>) the design effect equals 1, indicating that we are highly statistically efficient. The larger the value of <span class="math inline">\(\rho\)</span>, the higher <span class="math inline">\(D_{\text{eff}}\)</span> gets and the more inefficient our design.</p>
<p>We can flip this equation around to give us the ICC as a function of the design effect:</p>
<p><span class="math display">\[
\rho = \frac{D_{\text{eff}} - 1}{\bar{n} - 1}
\]</span></p>
<p>Complete the following R code to calculate the value of the ICC from the design effect:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>n_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(n)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>(Deff <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">/</span> (n_mean <span class="sc">-</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1315651</code></pre>
</div>
</div>
<p>But why did we bother working out the ICC? What advantage does this measure have over other measures like the design effect? To answer this, consider the following question:</p>
<p><strong>Question:</strong> Another study run in Kenya with a much larger sample size also found a design effect of <span class="math inline">\(D_{\text{eff}} = 12.79\)</span>. Does this mean the two countries have similar levels of intra-cluster correlation?</p>
<p><strong>Options:</strong></p>
<ul>
<li>Yes, the design effect is the same so the ICC must also be the same.</li>
<li>No, the design effect depends on the same size and so we cannot make this comparison. <strong>(correct)</strong></li>
</ul>
<p>The same value of <span class="math inline">\(\rho\)</span> can give very different values of <span class="math inline">\(D_{\text{eff}}\)</span>, depending on the sample size <span class="math inline">\(\bar{n}\)</span>. For this reason, we should be very careful when comparing the design effect between studies. Just because one study found a small design effect, does not mean that we can also assume the same small value when designing a new study. On the other hand, the ICC does not depend on the sample size and so tends to be more useful when comparing between studies.</p>
</section>
</section>
<section id="bonus-questions" class="level2">
<h2 class="anchored" data-anchor-id="bonus-questions">Bonus questions</h2>
<p>In an earlier module, you learned how to calculate a confidence interval (CI) on a prevalence estimate using the Wald interval. Use the information in <strong>Table 1</strong> to calculate a 95% CI around our global prevalence estimate. For the sample size, use the total sample size summed over all clusters. This is equivalent to assuming that all observations are completely independent. What do you get for the margin of error, and the lower and upper limits of your 95% CI?</p>
<p>Now repeat this analysis, but instead of using the total sample size, use the <em>effective</em> sample size that you calculated above. This analysis does not assume that all observations are independent, and instead takes account of over-dispersion. What do you get for the margin of error, and the lower and upper limits of your 95% CI? How does this compare with your previous answer?</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>