#!/usr/bin/env Rscript
prerender_all <- function(root) {
  path_tutorials <- file.path(root, "tutorials")
  stopifnot(file.exists(path_tutorials))
  paths <- dir(path_tutorials, full.names = TRUE)
  for (p in paths) {
    if (file.info(p)$isdir) {
      prerender(p)
    }
  }
}

with_dir <- function(path, code) {
  owd <- setwd(path)
  on.exit(setwd(owd))
  force(code)
}


prerender <- function(path) {
  files <- dir(path, "_(interactive|cb|tz)\\.Rmd$")
  for (f in files) {
    with_dir(path, rmarkdown::render(f))
  }
}

find_root <- function(args = commandArgs()) {
  re <- "^--file=(.+)$"
  i <- grep(re, args)
  stopifnot(length(i) >= 1)
  path_script <- normalizePath(sub(re, "\\1", args[[i[[1]]]]), mustWork = TRUE)
  dirname(path_script)
}


if (!interactive()) {
  prerender_all(find_root())
}
