---
title: "Scenario 3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(fontawesome)
```

## Background

You have been recruited by the National Malaria Control Programme (NMCP) of Cambodia to assist with study design. The NMCP is concerned about the potential spread of mutations that affect the performance of HRP2-based rapid diagnostic tests (RDTs). *pfhrp2* deletions can cause false-negative results in HRP2-based RDTs. In the last few weeks, there have been anecdotal reports of RDT failures in border towns, particularly in the Forest region. Additionally, there are concerns about the emergence of artemisinin resistance due to a new *pfk13* mutation, as neighboring countries have reported its increasing prevalence. Confirming whether this rare mutation is present in Cambodia is a priority for the NMCP. The NMCP plans to conduct a cross-sectional study to estimate the prevalence of *pfhrp2* deletions and detect the *pfk13* mutation. The NMCP are also interested to know the prevalence of other drug resistance mutations, such as *pfdhps*, *pfdhfr* and *pfcrt* mutations so these are secondary outcomes of interest.  

## Your task
The NMCP has a **budget of USD 500,000**. There are four regions in Cambodia (Coastal, Highland, Forest, and Urban) each with 25 health facilities. From previous studies conducted by the NMCP, we know that the **intra-cluster correlation is 0.1**. Your job is to design a study powered for the following end-points: 

- **Primary endpoints**
  - Estimate the prevalence of *pfhrp2* deletions causing false-negative RDTs
  - Detect the new *pfk13* mutation associated with artemisinin resistance.

- **Secondary endpoint**
  - Estimate the prevalence of *pfdhps*, *pfdhfr* and *pfcrt* mutations.

Each team member has key information on the epidemiological context, health facilities in each region, costing and sample size considerations (ICC, etc). Click on your role to access this information. Work in parellel (but together) to develop your study design! 

- [`r fa("chart-line")` **Epidemiologist**](sheet_1_cb.Rmd): Provide insights on disease prevalence and high-risk areas. 
- [`r fa("hospital")` **Health Facility Coordinator**](sheet_2_cb.Rmd): Offer logistical information about facilities.
- [`r fa("circle-dollar-to-slot")` **Budget Officer**](sheet_3_cb.Rmd): Manage financial aspects and calculate costs.
- [`r fa("calculator")` **Statistician**](https://shiny.dide.ic.ac.uk/mms-sd-workshop/module6-cb) (1-2 people): Handle sample size calculations and adjust for ICC.