---
title: 'Fact sheet: Budget officer'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(DT)
```

## Your role
As the budget officer on the team, your job is to help your team make informed decisions on costing and study design considerations, including: 

- Choosing (and potentially limiting) the number of regions or health facilities.
- Adjusting sample sizes, number of clusters, and timelines.
- Conducting cost calculations, for example: 
  - Total Fixed Costs = Number of HFs × (Fixed Cost per HF + Transport Cost per HF)
  - Total Variable Costs = Total Samples Enrolled × Variable Cost per Sample Enrollment Rate

Do your best job to stay within your budget! 

Navigate back to the [group activity instructions](module6_scenarios.Rmd) if you need to!

### Costs per item

| **Cost item**                           | **Cost** | **Description**                                       |
|-----------------------------------------|----------|-------------------------------------------------------|
| Fixed cost per health facility enrolled | $5,000   | Includes training, equipment, and administrative expenses. |
| Cost per sample enrolled       | $55      | Includes collection, laboratory testing, consumables, and data management. |

### Transport costs per health facility

| **Region**       | **Transport cost per health facility** |
|------------------|----------------------------------------|
| Coastal Region     | $1,000                                 |
| Highland Region     | $1,500                                 |
| Forest Region      | $2,500                                 |
| Urban Region      | $800                                   |